all: computeSalaries01 computeSalaries04 computeSalaries05 computeSalaries06 computeSalaries07 computeSalaries08 computeSalaries09 computeSalaries10 computeSalaries11 computeSalaries12 computeSalaries13 computeSalaries14 

.outputFolder:
	mkdir -p out

computeSalaries01: .outputFolder
	clang -std=c++17 -lstdc++ -lm computeSalaries_01_alpha.cpp -Wall -Wextra -Werror -o out/computeSalaries_01_alpha
	./out/computeSalaries_01_alpha
	
computeSalaries04: .outputFolder
	clang -std=c++17 -lstdc++ -lm computeSalaries_04_delta.cpp -Wall -Wextra -Werror -o out/computeSalaries_04_delta
	./out/computeSalaries_04_delta
	
computeSalaries05: .outputFolder
	clang -std=c++17 -lstdc++ -lm computeSalaries_05_epsilon.cpp -Wall -Wextra -Werror -o out/computeSalaries_05_epsilon
	./out/computeSalaries_05_epsilon
	
computeSalaries06: .outputFolder
	clang -std=c++17 -lstdc++ -lm computeSalaries_06_zeta.cpp -Wall -Wextra -Werror -o out/computeSalaries_06_zeta
	./out/computeSalaries_06_zeta
	
computeSalaries07: .outputFolder
	clang -std=c++17 -lstdc++ -lm computeSalaries_07_eta.cpp -Wall -Wextra -Werror -o out/computeSalaries_07_eta
	./out/computeSalaries_07_eta
	
computeSalaries08: .outputFolder
	clang -std=c++17 -lstdc++ -lm computeSalaries_08_theta.cpp -Wall -Wextra -Werror -o out/computeSalaries_08_theta
	./out/computeSalaries_08_theta
	
computeSalaries09: .outputFolder
	clang -std=c++17 -lstdc++ -lm computeSalaries_09_iota.cpp -Wall -Wextra -Werror -o out/computeSalaries_09_iota
	./out/computeSalaries_09_iota
	
computeSalaries10: .outputFolder
	clang -std=c++17 -lstdc++ -lm computeSalaries_10_kappa.cpp -Wall -Wextra -Werror -o out/computeSalaries_10_kappa
	./out/computeSalaries_10_kappa
	
computeSalaries11: .outputFolder
	clang -std=c++17 -lstdc++ -lm computeSalaries_11_lambda.cpp -Wall -Wextra -Werror -o out/computeSalaries_11_lambda
	./out/computeSalaries_11_lambda
	
computeSalaries12: .outputFolder
	clang -std=c++17 -lstdc++ -lm computeSalaries_12_my.cpp -Wall -Wextra -Werror -o out/computeSalaries_12_my
	./out/computeSalaries_12_my
	
computeSalaries13: .outputFolder
	clang -std=c++17 -lstdc++ -lm computeSalaries_13_ny.cpp -Wall -Wextra -Werror -o out/computeSalaries_13_ny
	./out/computeSalaries_13_ny
	
computeSalaries14: .outputFolder
	clang -std=c++17 -lstdc++ -lm computeSalaries_14_xi.cpp -Wall -Wextra -Werror -o out/computeSalaries_14_xi
	./out/computeSalaries_14_xi